-- begin MYTEST_INDIVIDUAL
alter table MYTEST_INDIVIDUAL add constraint FK_MYTEST_INDIVIDUAL_ID foreign key (ID) references MYTEST_CUSTOMER(ID)^
-- end MYTEST_INDIVIDUAL
-- begin MYTEST_COMPANY
alter table MYTEST_COMPANY add constraint FK_MYTEST_COMPANY_ID foreign key (ID) references MYTEST_CUSTOMER(ID)^
-- end MYTEST_COMPANY
-- begin MYTEST_EMPLOYEE
alter table MYTEST_EMPLOYEE add constraint FK_MYTEST_EMPLOYEE_CENTER foreign key (CENTER_ID) references MYTEST_CAR_SERVICE_CENTER(ID)^
create index IDX_MYTEST_EMPLOYEE_CENTER on MYTEST_EMPLOYEE (CENTER_ID)^
-- end MYTEST_EMPLOYEE
-- begin MYTEST_REPAIR
alter table MYTEST_REPAIR add constraint FK_MYTEST_REPAIR_CENTER foreign key (CENTER_ID) references MYTEST_CAR_SERVICE_CENTER(ID)^
create index IDX_MYTEST_REPAIR_CENTER on MYTEST_REPAIR (CENTER_ID)^
-- end MYTEST_REPAIR
-- begin MYTEST_CAR_SERVICE_CENTER_CUSTOMER_LINK
alter table MYTEST_CAR_SERVICE_CENTER_CUSTOMER_LINK add constraint FK_CARSERCENCUS_CAR_SERVICE_CENTER foreign key (CAR_SERVICE_CENTER_ID) references MYTEST_CAR_SERVICE_CENTER(ID)^
alter table MYTEST_CAR_SERVICE_CENTER_CUSTOMER_LINK add constraint FK_CARSERCENCUS_CUSTOMER foreign key (CUSTOMER_ID) references MYTEST_CUSTOMER(ID)^
-- end MYTEST_CAR_SERVICE_CENTER_CUSTOMER_LINK
-- begin MYTEST_REPAIR_EMPLOYEE_LINK
alter table MYTEST_REPAIR_EMPLOYEE_LINK add constraint FK_REPEMP_REPAIR foreign key (REPAIR_ID) references MYTEST_REPAIR(ID)^
alter table MYTEST_REPAIR_EMPLOYEE_LINK add constraint FK_REPEMP_EMPLOYEE foreign key (EMPLOYEE_ID) references MYTEST_EMPLOYEE(ID)^
-- end MYTEST_REPAIR_EMPLOYEE_LINK
-- begin MYTEST_CAR_SERVICE_CENTER
alter table MYTEST_CAR_SERVICE_CENTER add constraint FK_MYTEST_CAR_SERVICE_CENTER_CITY foreign key (CITY_ID) references MYTEST_CITY(ID)^
create index IDX_MYTEST_CAR_SERVICE_CENTER_CITY on MYTEST_CAR_SERVICE_CENTER (CITY_ID)^
-- end MYTEST_CAR_SERVICE_CENTER
-- begin MYTEST_CITY
create unique index IDX_MYTEST_CITY_UNIQ_NAME on MYTEST_CITY (NAME) ^
-- end MYTEST_CITY
