alter table MYTEST_EMPLOYEE add constraint FK_MYTEST_EMPLOYEE_CENTER foreign key (CENTER_ID) references MYTEST_CAR_SERVICE_CENTER(ID);
create index IDX_MYTEST_EMPLOYEE_CENTER on MYTEST_EMPLOYEE (CENTER_ID);
