alter table MYTEST_CAR_SERVICE_CENTER add constraint FK_MYTEST_CAR_SERVICE_CENTER_CITY foreign key (CITY_ID) references MYTEST_CITY(ID);
create index IDX_MYTEST_CAR_SERVICE_CENTER_CITY on MYTEST_CAR_SERVICE_CENTER (CITY_ID);
